languageCode = "en-us"
title = "Chicago Grown Up Science Fair"
baseurl = "https://grownupsciencefair.org/"
theme = "hugo-minimalist-theme"

[Params]
  header_title = "Chicago Grown Up Science Fair"
  header_background = "img/IMG_20160420_201854.jpg"
  custom_css = ["css/grownupsciencefair.css"]
  copyright = "Chicago Grown-Up Science Fair"
  custom_js = []
